Added test demonstrating a bug in `Pprintast`
Currently, `Pprintast` does not print `global_` on tupled constructor fields
correctly, and instead crashes.

```
% cat test.ml; echo; _install/bin/ocamlc -dsource test.ml
type t = C of global_ string

type t =
  | C of
  File "test.ml", line 1, characters 14-21:
  1 | type t = C of global_ string
                    ^^^^^^^
  Error: Tried to restore a saved location here, but none were found.
```

This is a regression from the previous broken behavior of printing the attribute
literally:

```
% cat test.ml; echo; ocamlc -dsource test.ml
type t = C of global_ string

type t =
  | C of ((string)[@extension.global ])
```

The next commit will fix `Pprintast` to have the correct behavior